[project]
name = "myne"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "uvicorn",
    "fastapi",
    "motor",
    "python-dotenv",
    "httpx",
    "python-dateutil",
    "python-multipart",
    "pydantic",
]